Document: pynx
Title: Debian pynx Manual
Author: <insert document author here>
Abstract: This manual describes what pynx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pynx/pynx.sgml.gz

Format: postscript
Files: /usr/share/doc/pynx/pynx.ps.gz

Format: text
Files: /usr/share/doc/pynx/pynx.text.gz

Format: HTML
Index: /usr/share/doc/pynx/html/index.html
Files: /usr/share/doc/pynx/html/*.html
